version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - client

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
